name: coala
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pytest
  - seaborn
  - pytorch
  - torchvision
  - tensorboard
  - joblib
  - tqdm
  - scikit-learn
  - pip
  - pip:
      - umap-learn
      - pytorch-lightning
      - -e .
