decoder_densify_mode: random
denoise: true
lr: 0.001
mask_ratio: 0.6
masked_loss_weight: 4.0
norm_type: rmsnorm
num_filters: 64
num_input_channels: 1
patch_size: 4
upconv_method: upsample+conv
use_skip: false
